pipeline{
    agent any
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clean") {
            steps {
                sh "mvn clean"
                
            }
        }
        stage("Test") {
            steps {
                sh "mvn test"
            }
        }
    }
}