pipeline{
    agent any
    stages {
        stage("Clean Up") {
            steps {
                deleteDir()
            }
        }
        stage("Clean") {
            steps {
                dir("serenity-web-training") {
                    sh "mvn clean"
                }
            }
        }
        stage("Test") {
            steps {
                sh "mvn test"
            }
        }
    }
}